# Generated by Django 6.1.1 on 2026-09-10 05:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('searched', 'Searched'), ('selected', 'Selected'), ('initiated', 'Initiated'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='searched', max_length=16)),
                ('ondc_transaction_id', models.CharField(max_length=64)),
                ('ondc_order_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=32)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='bookings.booking')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('ONDC:TRV10', 'Ride hailing')], default='ONDC:TRV10', max_length=32)),
                ('bpp_id', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('item_id', models.CharField(max_length=255)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eta_minutes', models.PositiveIntegerField()),
                ('raw_offer', models.JSONField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='bookings.trip')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='trip_leg',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='bookings.tripleg'),
        ),
    ]
