# Generated by Django 6.1.1 on 2026-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripleg',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='tripleg',
            name='mode',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tripleg',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tripleg',
            name='domain',
            field=models.CharField(choices=[('ONDC:TRV10', 'Ride hailing'), ('ONDC:TRV11', 'Metro / intracity bus'), ('ONDC:TRV12', 'Intercity bus / flight')], default='ONDC:TRV10', max_length=32),
        ),
    ]
