"""
Django settings for sarthi_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# 2026-09-10: this used to be a literal hardcoded key committed straight into this file —
# GitGuardian flagged it within minutes of the repo going public. Now read from DJANGO_SECRET_KEY
# if set (put a real one in your own .env for anything beyond a local clone-and-run), otherwise a
# fresh one is generated per process start — never a value that ends up in git history again.
from django.core.management.utils import get_random_secret_key  # noqa: E402

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'ondc_adapter',
    'mock_bpp',
    'trip_planner',
    'bookings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sarthi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sarthi_backend.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
}

# Local dev only — the Next.js dev server runs on :3000, Django on :8000.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:3000',
).split(',')

# ONDC/Beckn — demo keypairs for the local BAP <-> mock_bpp signing loop only; meaningless
# outside this local mock network (never registered with the real ONDC registry). These used
# to be committed literal key values here — GitGuardian flagged them as leaked secrets within
# minutes of the repo going public (commit 3cd205a). Real key material must never be hardcoded
# in a file that gets committed: set the *_PRIVATE_KEY/*_PUBLIC_KEY env vars yourself (a matched
# pair — see ondc_adapter.signing.generate_signing_keypair) for anything beyond a local
# clone-and-run; otherwise a fresh keypair is generated per process start below, never a value
# that ends up in git history.
from ondc_adapter.signing import generate_signing_keypair  # noqa: E402

ONDC_BAP_SUBSCRIBER_ID = os.environ.get('ONDC_BAP_SUBSCRIBER_ID', 'sarthi.example.bap')
ONDC_BAP_KEY_ID = os.environ.get('ONDC_BAP_KEY_ID', 'key1')
if os.environ.get('ONDC_BAP_PRIVATE_KEY') and os.environ.get('ONDC_BAP_PUBLIC_KEY'):
    ONDC_BAP_PRIVATE_KEY = os.environ['ONDC_BAP_PRIVATE_KEY']
    ONDC_BAP_PUBLIC_KEY = os.environ['ONDC_BAP_PUBLIC_KEY']
else:
    ONDC_BAP_PRIVATE_KEY, ONDC_BAP_PUBLIC_KEY = generate_signing_keypair()

ONDC_BPP_SUBSCRIBER_ID = os.environ.get('ONDC_BPP_SUBSCRIBER_ID', 'mock-bpp.example')
ONDC_BPP_KEY_ID = os.environ.get('ONDC_BPP_KEY_ID', 'key1')
if os.environ.get('ONDC_BPP_PRIVATE_KEY') and os.environ.get('ONDC_BPP_PUBLIC_KEY'):
    ONDC_BPP_PRIVATE_KEY = os.environ['ONDC_BPP_PRIVATE_KEY']
    ONDC_BPP_PUBLIC_KEY = os.environ['ONDC_BPP_PUBLIC_KEY']
else:
    ONDC_BPP_PRIVATE_KEY, ONDC_BPP_PUBLIC_KEY = generate_signing_keypair()

# BUILD_PLAN.md Phase 3 (live tracking): mock_bpp.store computes a confirmed order's CURRENT
# status from elapsed real time since confirmation (confirmed -> in_progress -> completed)
# rather than sitting at "confirmed" forever — see store.py. These are deliberately short so
# polling shows real, visible progression on a human timescale; a real ETA (minutes/hours) is
# not useful to wait out in a demo. Settings-driven (not module constants) so tests can shrink
# them to ~1-2s via override_settings without waiting out the real defaults.
MOCK_ORDER_IN_PROGRESS_AFTER_SECONDS = int(os.environ.get('MOCK_ORDER_IN_PROGRESS_AFTER_SECONDS', '8'))
MOCK_ORDER_COMPLETED_AFTER_SECONDS = int(os.environ.get('MOCK_ORDER_COMPLETED_AFTER_SECONDS', '20'))

# Points at THIS SAME server's /mock_bpp/ endpoints — see FEASIBILITY_RESEARCH.md #3
# and mock_bpp/README.md for why: no ONDC registry approval exists to point at a real
# gateway yet, so ondc_adapter.client talks to a same-process simulated seller instead.
# Swapping this URL for a real ONDC gateway's is a config change; see BUILD_PLAN.md
# Phase 4's readiness note for the ONE thing that's NOT just config (registering a real
# subscriber_id/FQDN so a real gateway can resolve where to send its own on_* callbacks).
ONDC_GATEWAY_BASE_URL = os.environ.get('ONDC_GATEWAY_BASE_URL', 'http://localhost:8000/mock_bpp')

# 2026-09-10 (BUILD_PLAN.md Phase 4 readiness): the real Beckn/ONDC protocol is
# asynchronous -- search()/select()/init()/confirm()/get_status() each get a bare ACK
# immediately, then the real result arrives later as a SEPARATE POST (on_search, etc.) to
# the caller's own registered callback base URL, carried in the outbound request's own
# context.bap_uri field. SARTHI_BASE_URL is what this project advertises as that bap_uri
# -- ondc_adapter/urls.py's on_search/on_select/on_init/on_confirm/on_status are where a
# real gateway (or, today, mock_bpp) actually calls back to. Must be a real,
# externally-reachable URL for real registry use (part of the FQDN/SSL requirement, see
# FEASIBILITY_RESEARCH.md #2) -- localhost is only meaningful for local dev/tests, which
# override it to LiveServerTestCase's own live_server_url (see ondc_adapter/tests).
SARTHI_BASE_URL = os.environ.get('SARTHI_BASE_URL', 'http://localhost:8000')

# How long mock_bpp deliberately waits before calling back — real (not zero) so the
# async round trip is genuinely exercised, short enough to stay human-watchable. Tests
# override this even shorter via override_settings.
MOCK_BPP_CALLBACK_DELAY_SECONDS = float(os.environ.get('MOCK_BPP_CALLBACK_DELAY_SECONDS', '0.3'))

# How long a client.py call will poll ondc_adapter's CallbackRecord table for the
# matching on_* callback before giving up with OndcRequestError. Must comfortably exceed
# MOCK_BPP_CALLBACK_DELAY_SECONDS (or a real gateway's real latency).
ONDC_CALLBACK_TIMEOUT_SECONDS = float(os.environ.get('ONDC_CALLBACK_TIMEOUT_SECONDS', '5'))


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# 2026-09-10 Turso spike (FEASIBILITY_RESEARCH.md #5): django_pyturso is a real,
# community-maintained Django backend for Turso's embedded libSQL engine (local file,
# not the hosted edge service — that needs a separate sync step django_pyturso doesn't
# handle). Confirmed working here: migrations, UUID/JSONField/DecimalField model fields
# (bookings.models) and FK constraints all ran clean in the spike below. DJANGO_DB_ENGINE
# lets `pytest`/CI swap to plain sqlite3 without code changes if Turso ever regresses.
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DJANGO_DB_ENGINE', 'django_pyturso'),
        'NAME': str(BASE_DIR / 'db.turso'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
