"""
Django settings for sarthi_backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# 2026-09-10: this used to be a literal hardcoded key committed straight into this file —
# GitGuardian flagged it within minutes of the repo going public. Now read from DJANGO_SECRET_KEY
# if set (put a real one in your own .env for anything beyond a local clone-and-run), otherwise a
# fresh one is generated per process start — never a value that ends up in git history again.
from django.core.management.utils import get_random_secret_key  # noqa: E402

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'ondc_adapter',
    'mock_bpp',
    'trip_planner',
    'bookings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sarthi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sarthi_backend.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],
}

# Local dev only — the Next.js dev server runs on :3000, Django on :8000.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:3000',
).split(',')

# ONDC/Beckn — demo keypairs for the local BAP <-> mock_bpp signing loop only; meaningless
# outside this local mock network (never registered with the real ONDC registry). These used
# to be committed literal key values here — GitGuardian flagged them as leaked secrets within
# minutes of the repo going public (commit 3cd205a). Real key material must never be hardcoded
# in a file that gets committed: set the *_PRIVATE_KEY/*_PUBLIC_KEY env vars yourself (a matched
# pair — see ondc_adapter.signing.generate_signing_keypair) for anything beyond a local
# clone-and-run; otherwise a fresh keypair is generated per process start below, never a value
# that ends up in git history.
from ondc_adapter.signing import generate_signing_keypair  # noqa: E402

ONDC_BAP_SUBSCRIBER_ID = os.environ.get('ONDC_BAP_SUBSCRIBER_ID', 'sarthi.example.bap')
ONDC_BAP_KEY_ID = os.environ.get('ONDC_BAP_KEY_ID', 'key1')
if os.environ.get('ONDC_BAP_PRIVATE_KEY') and os.environ.get('ONDC_BAP_PUBLIC_KEY'):
    ONDC_BAP_PRIVATE_KEY = os.environ['ONDC_BAP_PRIVATE_KEY']
    ONDC_BAP_PUBLIC_KEY = os.environ['ONDC_BAP_PUBLIC_KEY']
else:
    ONDC_BAP_PRIVATE_KEY, ONDC_BAP_PUBLIC_KEY = generate_signing_keypair()

ONDC_BPP_SUBSCRIBER_ID = os.environ.get('ONDC_BPP_SUBSCRIBER_ID', 'mock-bpp.example')
ONDC_BPP_KEY_ID = os.environ.get('ONDC_BPP_KEY_ID', 'key1')
if os.environ.get('ONDC_BPP_PRIVATE_KEY') and os.environ.get('ONDC_BPP_PUBLIC_KEY'):
    ONDC_BPP_PRIVATE_KEY = os.environ['ONDC_BPP_PRIVATE_KEY']
    ONDC_BPP_PUBLIC_KEY = os.environ['ONDC_BPP_PUBLIC_KEY']
else:
    ONDC_BPP_PRIVATE_KEY, ONDC_BPP_PUBLIC_KEY = generate_signing_keypair()

# Points at THIS SAME server's /mock_bpp/ endpoints — see FEASIBILITY_RESEARCH.md #3
# and mock_bpp/README.md for why: no ONDC registry approval exists to point at a real
# gateway yet, so ondc_adapter.client talks to a same-process simulated seller instead.
# Swapping this for the real ONDC gateway later is a config change, not a rewrite —
# see ARCHITECTURE.md's isolation principle.
ONDC_GATEWAY_BASE_URL = os.environ.get('ONDC_GATEWAY_BASE_URL', 'http://localhost:8000/mock_bpp')


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# 2026-09-10 Turso spike (FEASIBILITY_RESEARCH.md #5): django_pyturso is a real,
# community-maintained Django backend for Turso's embedded libSQL engine (local file,
# not the hosted edge service — that needs a separate sync step django_pyturso doesn't
# handle). Confirmed working here: migrations, UUID/JSONField/DecimalField model fields
# (bookings.models) and FK constraints all ran clean in the spike below. DJANGO_DB_ENGINE
# lets `pytest`/CI swap to plain sqlite3 without code changes if Turso ever regresses.
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DJANGO_DB_ENGINE', 'django_pyturso'),
        'NAME': str(BASE_DIR / 'db.turso'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
