# Generated by Django 6.1.1 on 2026-09-10 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.CharField(max_length=32)),
                ('message_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('transaction_id', 'action', 'message_id')},
            },
        ),
    ]
